apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app: modix-translator-bot
  name: modix-translator-bot
  namespace: csharp
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: modix-translator-bot
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: modix-translator-bot
    spec:
      automountServiceAccountToken: false
      containers:
      - env:
        - name: COREHOST_TRACE
          value: "0"
        - name: BOT_DISCORDTOKEN
          valueFrom:
            secretKeyRef:
              key: discord-bot-token
              name: modix
        - name: BOT_AZURETRANSLATIONKEY
          valueFrom:
            secretKeyRef:
              key: azure-translation-service-key
              name: modix
        image: cisien/modix-translator:latest
        imagePullPolicy: Always
        name: modix-translator
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File    
      dnsPolicy: ClusterFirst
      nodeSelector:
        beta.kubernetes.io/os: linux
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      shareProcessNamespace: true
      terminationGracePeriodSeconds: 30